### ISSUE TITLE
resources img doesnt show up

### ISSUE THREAD

**Issue by shinkthr** [antedoro/arberia#16]
i want to show image post on `posts/title.md`
```
resources:
  - name: "featured-image"
    src: "/img/featured-image.png"
  - name: "featured-image-preview"
    src: "/img/featured-image.png"
```
but it doesnt show up
